### ISSUE TITLE
multipart/form-data post  error

### ISSUE THREAD

**Issue by xinqiyang** [liseen/lua-resty-http#12]
依旧是一个 multipart/form-data的出错问题.....

现在拼装了一个请求
- Table String:
  |    { [table: 0x41dead18, 13 item(s)]
  |    |   *max_body_size =>  1073741824
  |    |   *fetch_size    =>  16384
  |    |   *uri   =>  /submit
  |    |   *timeout   =>  100
  |    |   *headers   =>
  |    |    { [table: 0x41de7e60, 6 item(s)]
  |    |    |   *host =>  localhost
  |    |    |   *content-type =>  multipart/form-data; boundary=BOUNDARY-OOYZUGIKJHFFZAFM-BOUNDARY
  |    |    |   *connection   =>  close, TE
  |    |    |   *content-length   =>  34761
  |    |    |   *te   =>  trailers
  |    |    |   *user-agent   =>  resty.http/0.2
  |    |    }
  |    |   *host  =>  localhost
  |    |   *method    =>  POST
  |    |   *scheme    =>  http
  |    |   *authority =>  localhost:9333
  |    |   *url   =>  http://localhost:9333/submit
  |    |   *body  =>  --BOUNDARY-OOYZUGIKJHFFZAFM-BOUNDARY
  content-disposition: form-data; name="myfile"; filename="portrait"
  content-type: application/octet-stream
  content-transfer-encoding: binary

����JFIF``��C

可是调用发送的时候

local ok, code, headers, status, body  = hc:request {
            url = weedfsurl.submit,
            timeout = 100,
            method = "POST",
            headers = rq.headers,
            body = rq.source
        }

返回结果是 ,我这里的存储后端是 weedfs , 使用的端口是 127.0.0.1:9333 的了.
这里竟然socket链接不上......

sock connected failed localhost could not be resolved (110: Operation timed out)

这里发送请求貌似不靠谱啊...针对multipart/form-data的请求,请大家提供一些思路吧..

谢谢.

**Comment by FMLS** [comment]
@xinqiyang 请问multipart-post.lua是哪个项目中的文件，我现在使用的一个lua-resty-http库好像不能支持发送multipart/form-data形式的body体
