### ISSUE TITLE
SSL handshake problem

### ISSUE THREAD

**Issue by thefosk** [liseen/lua-resty-http#31]
I'm receiving the following error when trying to consume an SLL endpoint (the GitHub API):

```
2015/02/18 11:06:01 [error] 3087#0: *28889 SSL_do_handshake() failed (SSL: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol), client: 52.1.6.14, server: , request: "POST /oauth_url HTTP/1.1", host: "mashaper-github.p.mashape.com"
```

I found somewhere that this problem could be releated to this:

> This error happens when OpenSSL receives something other than a ServerHello in a protocol version it understands from the server. It can happen if the server answers with a plain (unencrypted) HTTP. It can also happen if the server only supports e.g. TLS 1.2 and the client does not understand that protocol version. Normally, servers are backwards compatible to at least SSL 3.0 / TLS 1.0, but maybe this specific server isn't (by implementation or configuration).

**Comment by thefosk** [comment]
This problem doesn't happen if I append the 443 port to the URL like `https://url:443/dosomething`

**Comment by agentzh** [comment]
Seems like this library does not set the default port number right for `https://`.

**Comment by naruto1021** [comment]
This does not resolve the problem, need to reset the port number 443 before connect host
local code, headers, status, body, bytes, ok, err

    local nreqt = adjustrequest(reqt)
	
	if nreqt.scheme == 'https' then
		nreqt.port = SSL_PORT;
	end

    local sock = tcp()
    if not sock then
        return nil, "create sock failed"
    end

   sock:settimeout(nreqt.timeout)

    -- connect
    ok, err = sock:connect(nreqt.host, nreqt.port)
    if err then
        return nil, "sock connected failed " .. err
    end
