### ISSUE TITLE
I have this code , its return NIL

### ISSUE THREAD

**Issue by ryannining** [liseen/lua-resty-http#33]
```
local http = require("resty.http")
local hc = http:new()
local ok, code, headers, status, body = hc:request({
  url = "http://www.tokoled.net/uploads/1920.jpg",
  method = "GET",
  headers = { },
  body = ""
})
return ngx.say(body)
```

Are my code correct ? i have new project to migrate my other website to LUA+ OpenResty, but it need phpcurl, so i think this package is suitable to replace phpcurl function.

**Comment by wendal** [comment]
ngx.say always return nil, what is the point??

**Comment by ryannining** [comment]
oh sorry, wrong code

```
ngx.say(body)
```

Body is nil ? is it correct way ? i am trying to load image from other website and process is in my app code.

**Comment by ryannining** [comment]
i try to ngx.say all result from the request function
```
ngx.say(ok,code,headers,status,body)
```

Result:
nilsock connected failed no resolver defined to resolve "www.tokoled.net"nilnilnil

**Comment by wendal** [comment]
add above config into nginx.conf 

```
resolver 8.8.8.8; 
```

**Comment by ryannining** [comment]
THX
